export class Item {
  constructor(
    public id: number,
    public name: string,
    public description: string,
    public price: number,
    public stock: number,
    public isActive: boolean = true,
    public createdAt: Date = new Date(),
    public updatedAt: Date = new Date(),
  ) {}

  // Helper method to create new items without ID
  static create(newItem: Omit<Item, 'id' | 'createdAt' | 'updatedAt'>): Item {
    return new Item(
      0, // Temporary ID - will be generated by ApiService
      newItem.name,
      newItem.description,
      newItem.price,
      newItem.stock,
      newItem.isActive,
    );
  }
}

export interface ItemCreateDto {
  name: string;
  description: string;
  price: number;
  stock: number;
  isActive?: boolean;
}

export interface ItemUpdateDto extends Partial<ItemCreateDto> {
  id: number;
}
