import { Item } from './item.model';

export class Sale {
  constructor(
    public id: number,
    public itemId: number,
    public itemName: string, // Denormalized for easier display
    public quantity: number,
    public unitPrice: number,
    public total: number,
    public date: string, // ISO string format
    public userId: number,
    public userName: string, // Denormalized for easier display
  ) {}

  // Helper method to create new sales without ID
  static create(
    item: Item,
    quantity: number,
    userId: number,
    userName: string,
  ): Sale {
    return new Sale(
      0, // Temporary ID - will be generated by ApiService
      item.id,
      item.name,
      quantity,
      item.price,
      quantity * item.price,
      new Date().toISOString(),
      userId,
      userName,
    );
  }
}

export interface SaleCreateDto {
  itemId: number;
  quantity: number;
  userId: number;
}

export interface SaleDto {
  id: number;
  itemId: number;
  itemName: string;
  quantity: number;
  unitPrice: number;
  total: number;
  date: string;
  userId: number;
  userName: string;
}
